# Generated by Django 5.0.6 on 2024-07-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=30)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("C++", "C++"),
                            ("Java", "Java"),
                            ("Python", "Python"),
                            ("Typescript", "Typescript"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.CharField(help_text="Duration in Weeks", max_length=10),
                ),
            ],
        ),
    ]
